### PR TITLE
Migrate to Nest8

### PR DESCRIPTION
**Pull request by Minishlink**
Will fix typings tomorrow

### CODE REVIEW

**Comment by Rmannn** [comment]
I will configure tests to run againsts PR tomorrow as well.
Thx for this PR.

**Comment by Minishlink** [comment]
Should be good :)

**Comment by Rmannn** [comment]
Please can you rebase master to get the last config of the workflow to let the tests run on this pr ?

**Comment by Rmannn** [comment]
All good !

**Pull request merged**
