### PR TITLE
chore(packages): prettier should be a development dependency

### PR DESCRIPTION
**Pull request by geersch**
## Description

- **chore(pipelines)**: `prettier` is now registered as a development dependency.

### CODE REVIEW

**Comment by Rmannn** [comment]
Sorry but Prettier is a dependency, actually used as an helper to format json response in the cli.
Maybe we should make it optional ?

**Comment by geersch** [comment]
Indeed, I see it is used here:

https://github.com/Pop-Code/nestjs-console/blob/master/src/helpers.ts

The `formatResponse` function is only used in one place.

https://github.com/Pop-Code/nestjs-console/blob/a32d2653cb507a4eaf5c2a2fa0404c77c3057f8e/src/service.ts#L56

I noticed `prettier` was not removed when I pruned my development dependencies. Seems a bit much to require users to pull in `prettier` as a dependency. 

If all you want is to pretty print the error, you could use `JSON.stringify` with a custom replacer.

```ts
function replaceErrors(key, value) {
    if (value instanceof Error) {
        var error = {};

        Object.getOwnPropertyNames(value).forEach(function (key) {
            error[key] = value[key];
        });

        return error;
    }

    return value;
}

var error = new Error('testing');
console.error(JSON.stringify(error, replaceErrors, 2));
```

This outputs:

```shell
{
  "stack": "Error: testing\n    at <anonymous>:15:13",
  "message": "testing"
}
```

If you only want the stack trace, then the following suffices:

```
> console.error(new Error('Testing').stack);
Error: Testing
    at repl:1:15
    at Script.runInThisContext (vm.js:122:20)
    at REPLServer.defaultEval (repl.js:332:29)
    at bound (domain.js:402:14)
    at REPLServer.runBound [as eval] (domain.js:415:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:203:15)
```

**Comment by Rmannn** [comment]
JSON.stringify will not pretiffy the code. That depends on the shell you use.
We have projects were we prettify a cli response that is not an error in our command handler.

However I understand the pb. I will made prettier optional in the next release.
This will remove an exported function and will introduce a Breaking change. We will need a new major release.

**Comment by geersch** [comment]
Ok, thanks for the fast feedback. I'll close this PRQ. I'll wait for the update.
In our case we don't require prettier to format messages. I was creating a Docker image and trying to keep it as small as possible. While cleaning / pruning the Docker images I noticed prettier was being installed, which took up 12MB. Hence, the PRQ.

**Comment by Rmannn** [comment]
Hi, Prettier is now a dev dependency in v4.0.0. We use JSON.stringify to format response. You were right, the third argument allow us to format the response.
Thx for your feedback.

**Pull request closed without merging**
